"""Starter `.crl` templates emitted by `circlelib new`.

Three templates are shipped:

- ``default`` — a single Sphere + Cube under a Group, suitable as a
  blank canvas.
- ``anim`` — a scene with one labelled Sphere and an ``animate{}``
  block driving its position with the ``ease_in_out`` easing.
- ``stdlib`` — imports `@stdlib/furniture/chair` and renders the
  Chair component, demonstrating the standard library prefix.

Each template is a plain UTF-8 string with a leading comment header.
The CLI handles file I/O, extension auto-append, and the
no-overwrite-by-default rule.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict


# Templates use the literal sentinel `<NAME>` for the per-file name
# substitution; nothing else is interpolated. We use `.replace()` rather
# than `.format()` so brace-heavy `.crl` source can be written naturally
# (no `{{ }}` doubling) and so file names containing `{` or `}` don't
# blow up the substitution.
_NAME_SENTINEL = "<NAME>"

_TEMPLATES: Dict[str, str] = {
    "default": """\
// <NAME> — generated by `circlelib new`.
//
// Run:  circlelib run <NAME>.crl
//
// Drag the left mouse button to orbit, scroll to zoom, ESC to quit.
// Press P at any time to snap a screenshot under ./screenshots/.

scene {
    Group(position=(0, 0, 0)) {
        Sphere(radius=1.0, position=(-1.5, 1.0, 0), color=#3aa0ff)
        Cube(width=1.6, height=1.6, depth=1.6, position=(1.5, 0.8, 0), color=#ff5577)
    }
}
""",
    "anim": """\
// <NAME> — generated by `circlelib new --template anim`.
//
// Run:  circlelib run <NAME>.crl
// Record:  circlelib record <NAME>.crl --out clip.mp4 --duration 4

scene {
    ball = Sphere(radius=0.6, position=(-5, 0.6, 0), color=#3aa0ff)
}

animate {
    duration = 4
    ball.position = anim(t, (-5, 0.6, 0), (5, 0.6, 0), 4, easing=ease_in_out)
}
""",
    "stdlib": """\
// <NAME> — generated by `circlelib new --template stdlib`.
//
// Imports a component from the shipped stdlib catalog and drops it in
// at the origin. See `circlelib/stdlib/README.md` for the full list.

import "@stdlib/furniture/chair" as ch
import "@stdlib/geometry/axes"   as ax

scene {
    ax.Axes(position=(0, 0, 0))
    ch.Chair(position=(2, 0, 0))
}
""",
}


class ScaffoldError(RuntimeError):
    pass


def list_templates() -> list[str]:
    return sorted(_TEMPLATES.keys())


def write_scaffold(
    path: Path,
    *,
    template: str = "default",
    force: bool = False,
) -> Path:
    """Write the requested template to `path` and return the resolved path.

    Behaviour:
    - A `.crl` extension is auto-appended if missing.
    - The file is not overwritten unless `force=True`.
    - Parent directory is created if needed.
    - Returns the absolute resolved path of the written file.
    """
    if template not in _TEMPLATES:
        raise ScaffoldError(
            f"unknown template '{template}'. Choose from: "
            f"{', '.join(list_templates())}"
        )
    target = Path(path)
    if target.suffix == "":
        target = target.with_suffix(".crl")
    target = target.resolve()
    if target.exists() and not force:
        raise ScaffoldError(
            f"{target} already exists. Pass --force to overwrite."
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    body = _TEMPLATES[template].replace(_NAME_SENTINEL, target.stem)
    target.write_text(body)
    return target
